apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: sample-api
  name: sample-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: sample-api
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: sample-api
    spec:
      containers:
      - image: saeedmaghdam/sample-api:36
        name: sample-api
        resources: {}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  name: lb-service
  labels:
    app: lb-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: sample-api
